import Head from "next/head";
import Container from "@/components/container/Container";
import BlogsPrimary from "@/components/blogs/blogs-primary/BlogsPrimary";
import BlogsSecondary from "@/components/blogs/blogs-secondary/BlogsSecondary";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <BlogsPrimary></BlogsPrimary>
        <BlogsSecondary></BlogsSecondary>
        <BlogsPrimary></BlogsPrimary>
        <BlogsSecondary></BlogsSecondary>
      </Container>
    </>
  );
}
