import Head from "next/head";
import type { ReactElement } from "react";
import type { NextPageWithLayout } from "./_app";
import Layout from "@/components/layout/Layout";
import Container from "@/components/container/Container";
import BlogsPrimary from "@/components/blogs/blogs-primary/BlogsPrimary";
import BlogsSecondary from "@/components/blogs/blogs-secondary/BlogsSecondary";

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Glitch</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <BlogsPrimary></BlogsPrimary>
        <BlogsSecondary></BlogsSecondary>
        <BlogsPrimary></BlogsPrimary>
        <BlogsSecondary></BlogsSecondary>
      </Container>
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Home;
